### ISSUE TITLE
Error in sending message

### ISSUE THREAD

**Issue by yosefarr** [rhavyn/norbert#6]
Hi My Name is Yosef, and i'm trying to work with norbert:
As a test i'm running the NorbertJavaNetworkClientMain and NorbertJavaNetworkServerMain 
I have a problem when i send a message from the Client to the server - in the zookeeper i;m getting the exception:
<B>
java.io.IOException: Unreasonable length = 1701999662
        at org.apache.jute.BinaryInputArchive.readBuffer(BinaryInputArchive.java:100)
        at org.apache.zookeeper.proto.ConnectRequest.deserialize(ConnectRequest.java:89)
        at org.apache.zookeeper.server.NIOServerCnxn.readConnectRequest(NIOServerCnxn.java:733)
        at org.apache.zookeeper.server.NIOServerCnxn.readPayload(NIOServerCnxn.java:485)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:521)
        at org.apache.zookeeper.server.NIOServerCnxn$Factory.run(NIOServerCnxn.java:262)<B>

And the server code never reach the message function handler

can you help?

Thanks,
Yosef

**Comment by eggiant** [comment]
Norbert team,

Any hints on this issue?  I keep getting the same problem running the example project.

Java 1.7 64bit on Win7.

Would really appreciate some help.

Cheers
Ant

**Comment by jhartman** [comment]
This fork is literally years old. Have you tried the one at https://github.com/linkedin-sna/norbert?

**Comment by eggiant** [comment]
Hi,

Yes, I clocked that the fork was old today. Was going to reply to my original question this evening. 

The current/live version, does that have the version of any launcher in the build folder?

Thanks for coming back to me so quickly. 

Regards, 
Ant

----- Reply message -----
From: "Joshua Hartman" reply@reply.github.com
To: "Ant Eggington" anthony.eggington@btopenworld.com
Subject: [norbert] Error in sending message (#6)
Date: Mon, Jun 25, 2012 17:37

This fork is literally years old. Have you tried the one at https://github.com/linkedin-sna/norbert?

---
